# Generated by Django 4.1.5 on 2023-03-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
