# Generated by Django 4.1.5 on 2023-03-05 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_time', models.TimeField()),
                ('desired_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_course', models.CharField(max_length=20)),
                ('quantiity_watch', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Listeners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=20, null=True)),
                ('year_of_birth', models.DateField()),
                ('image', models.ImageField(upload_to='')),
                ('phone', models.CharField(max_length=12)),
                ('сompleted_courses', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mentors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('year_of_birth', models.DateField()),
                ('qualification', models.CharField(max_length=30)),
                ('additional_information', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_time', models.DateField()),
                ('desired_date', models.TimeField()),
                ('name_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itea_center.course')),
                ('name_listen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itea_center.application')),
                ('name_mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itea_center.mentors')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='name_listeners',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itea_center.listeners'),
        ),
        migrations.AddField(
            model_name='application',
            name='name_of_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itea_center.course'),
        ),
    ]
