# Generated by Django 4.1.5 on 2023-03-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itea_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Заявки', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курсы', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name': 'Группы', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='listeners',
            options={'verbose_name': 'Слушатели', 'verbose_name_plural': 'Слушатели'},
        ),
        migrations.AlterModelOptions(
            name='mentors',
            options={'verbose_name': 'Менторы', 'verbose_name_plural': 'Менторы'},
        ),
        migrations.RemoveField(
            model_name='application',
            name='desired_date',
        ),
        migrations.AddField(
            model_name='application',
            name='desired_week',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='desired_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mentors',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
