# Generated by Django 4.1.5 on 2023-03-12 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itea_center', '0002_alter_application_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='name_listeners',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itea_center.listeners'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name_of_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itea_center.course'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='desired_date',
            field=models.CharField(max_length=100),
        ),
    ]
