# Generated by Django 4.1.5 on 2023-03-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itea_center', '0003_alter_application_name_listeners_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='quantiity_watch',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='desired_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='desired_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='listeners',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='listeners',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='listeners',
            name='year_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='listeners',
            name='сompleted_courses',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mentors',
            name='additional_information',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mentors',
            name='year_of_birth',
            field=models.DateField(null=True),
        ),
    ]
